### ISSUE TITLE
Can documents be stored in their own hashset?

### ISSUE THREAD

**Issue by goleafs** [DevExpress/aspnet-office-solutions#1]
Documents and keys are all stored in the root of db0, making it quite messy.  Normally we group all related cache data into its own hashset.  
Can this be made configurable?
![redis](https://user-images.githubusercontent.com/5503729/38100034-32044662-334a-11e8-820d-3def98a51d67.png)

**Comment by SergeySeleznyov** [comment]
Hello @goleafs,

There is no setting about that. But the RedisOfficeStateProvider project contains all the required source code publicly available. The file that may be helpful for the task you mentioned is here:

aspnet-office-solutions/RedisOfficeStateProvider/src/RedisImplementation.cs
 
You can find Lua scripts that are responsible for the data exchange with Redis in this file.
Please pay attention to the construction as follows:
 
`redis.call('some_command_name')`
 
Current commands like SET/GET (and others) work with just key-value pairs. 
Please feel free to substitute them with their analogues that work with hash.
 
You may find the following documentation article to be useful:
https://redis.io/commands#hash

In addition, pay attention to the specifics of setting expiration for the hash keys:
https://github.com/antirez/redis/issues/167
