### ISSUE TITLE
no support for cluster?

### ISSUE THREAD

**Issue by goleafs** [DevExpress/aspnet-office-solutions#2]
Looks like there is no support for Redis  cluster?

this is a valid connection string set to use a cluster:
connection="redis1:7000,redis2:7000,abortConnect=false,connectTimeout=5000,syncTimeout=5000"

But when reusing this for the devExpress Redis Provider we get:
Multi-key operations must involve a single slot; keys can use 'hash tags' to help this, i.e. '{/users/12345}/account' and '{/users/12345}/contacts' will always be in the same slot

**Comment by SergeySeleznyov** [comment]
Hello @goleafs,

In a current state the RedisOfficeStateProvider does not support the Redis cluster.

According the to Redis documentation:
[Redis Cluster Specification](https://redis.io/topics/cluster-spec)

it is possible to use multi-key operation using the "hash tags".

Please, look at the following file:

aspnet-office-solutions/RedisOfficeStateProvider/src/RedisImplementation.cs

You can modify the Lua scripts according to your task.
